include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - sort_pub_dependencies
    - require_trailing_commas
    - avoid_unnecessary_containers
    - prefer_is_empty
    - prefer_is_not_empty
    - use_key_in_widget_constructors
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
